import React from 'react'
import { Sparkles } from 'lucide-react'

interface PolicySection {
  id: string
  title: string
  content: string[]
}

export const TermsConditions: React.FC = () => {
  const sections: PolicySection[] = [
    {
      id: 'service-use',
      title: 'Service Use',
      content: [
        'IndyLaw grants you a limited, non-exclusive, non-transferable license to access and use the platform for your internal legal practice purposes.',
        'You must be at least 18 years of age and a qualified legal professional or authorised representative of a legal entity to use IndyLaw.',
        'You agree not to use IndyLaw for any unlawful purpose, or in a way that infringes the rights of any third party.',
        'You are responsible for maintaining the confidentiality of your account credentials. You must notify us immediately at security@indylaw.in if you suspect unauthorised access to your account.',
        'IndyLaw is a research and drafting assistance tool. All AI-generated outputs must be reviewed and validated by a qualified legal practitioner before use in any legal proceeding.'
      ]
    },
    {
      id: 'intellectual-property',
      title: 'Intellectual Property',
      content: [
        'The IndyLaw platform, including all software, designs, AI models, indices, and interfaces, is owned exclusively by IndyLaw Technologies Private Limited and protected under applicable intellectual property laws.',
        'Content you upload to IndyLaw (judgments, contracts, internal documents) remains your property. By uploading, you grant IndyLaw a limited licence to process and store that content solely to provide you with the requested services.',
        'AI-generated drafts, research summaries, and platform outputs produced using IndyLaw are considered work product delivered to you. You retain the right to use, edit, and submit these outputs subject to professional validation.',
        'You may not copy, reverse-engineer, decompile, or create derivative works from any part of the IndyLaw platform without our express written consent.'
      ]
    },
    {
      id: 'limitation',
      title: 'Limitation of Liability',
      content: [
        'IndyLaw is provided "as is" and "as available." We make no warranties — express or implied — regarding the accuracy, completeness, or fitness for a particular purpose of any output generated by the platform.',
        'IndyLaw shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of or inability to use the service.',
        'Our total cumulative liability to you for any claim arising under these Terms shall not exceed the total fees paid by you for the service in the three months preceding the claim.',
        'We do not guarantee that the platform will be free from errors or uninterrupted. Scheduled maintenance windows will be communicated with at least 24 hours advance notice where possible.'
      ]
    },
    {
      id: 'payment',
      title: 'Payment & Subscriptions',
      content: [
        'Subscription fees are billed in advance on a monthly or annual basis as selected during sign-up.',
        'All prices are listed in Indian Rupees (INR) and exclude applicable Goods and Services Tax (GST).',
        'You may cancel your subscription at any time. Cancellations take effect at the end of the current billing period; no refunds are issued for partial periods.',
        'We reserve the right to modify pricing with at least 30 days\' advance written notice. Continued use after the notice period constitutes acceptance of the new pricing.'
      ]
    },
    {
      id: 'termination',
      title: 'Termination',
      content: [
        'Either party may terminate this agreement at any time. You may terminate by cancelling your subscription. We may terminate or suspend access immediately if you violate these Terms.',
        'Upon termination, your right to access the platform ceases. You may request an export of your data within 30 days of termination, after which your data will be permanently deleted.',
        'Sections related to intellectual property, limitation of liability, and dispute resolution shall survive termination.'
      ]
    },
    {
      id: 'changes',
      title: 'Changes to Terms',
      content: [
        'We reserve the right to update these Terms at any time. We will provide at least 30 days\' notice of material changes via email and an in-platform notification.',
        'If you do not agree to the updated Terms, you must stop using the platform and cancel your subscription before the effective date of the changes.',
        'Your continued use of IndyLaw after the effective date of any update constitutes acceptance of the revised Terms.',
        'These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in New Delhi, India.'
      ]
    }
  ]

  return (
    <div className="bg-[#FAF9F6] min-h-screen text-[#111827] font-sans selection:bg-[#D4AF37]/30 selection:text-[#0B132B]">
      {/* Hero */}
      <section className="relative pt-32 pb-16 px-6 overflow-hidden bg-[#0B132B] text-white border-b border-[#D4AF37]/20">
        <div className="absolute inset-0 bg-grid-dots opacity-[0.03] pointer-events-none" />
        <div className="max-w-4xl mx-auto text-center space-y-6 relative z-10">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-white/5 border border-white/10 rounded-full text-[10px] font-bold text-[#D4AF37] uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5" /> Legal
          </div>
          <h1 className="text-4xl sm:text-5xl font-serif font-bold text-white tracking-tight">Terms & Conditions</h1>
          <p className="text-xs text-[#FAF9F6]/70">Last updated: June 2026 · IndyLaw Technologies Private Limited</p>
        </div>
      </section>

      {/* Content */}
      <section className="py-20 px-6 max-w-4xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-10">
          {/* Table of Contents */}
          <aside className="lg:col-span-1 hidden lg:block">
            <div className="sticky top-28 space-y-1">
              <p className="text-[10px] font-black text-[#D4AF37] uppercase tracking-widest mb-3">Contents</p>
              {sections.map((sec) => (
                <a
                  key={sec.id}
                  href={`#${sec.id}`}
                  className="block text-[11px] text-[#4B5563] hover:text-[#0B132B] font-medium py-0.5 transition-colors border-l-2 border-transparent hover:border-[#D4AF37] pl-3"
                >
                  {sec.title}
                </a>
              ))}
            </div>
          </aside>

          {/* Terms Body */}
          <div className="lg:col-span-3 space-y-12">
            <p className="text-xs text-[#4B5563] leading-relaxed border-l-4 border-[#D4AF37] pl-4 italic bg-white rounded-r-xl py-3 pr-4">
              These Terms and Conditions ("Terms") govern your access to and use of the IndyLaw platform operated by IndyLaw Technologies Private Limited ("IndyLaw"). By creating an account or using our services, you agree to be bound by these Terms.
            </p>

            {sections.map((sec) => (
              <div key={sec.id} id={sec.id} className="space-y-4 scroll-mt-28">
                <h2 className="text-xl font-bold text-[#0B132B] font-serif border-b border-[#0B132B]/10 pb-3">
                  {sec.title}
                </h2>
                <ul className="space-y-3">
                  {sec.content.map((para, i) => (
                    <li key={i} className="flex gap-3 text-xs text-[#4B5563] leading-relaxed">
                      <span className="w-1.5 h-1.5 rounded-full bg-[#D4AF37] mt-1.5 flex-shrink-0" />
                      <span>{para}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}

            <div className="bg-[#0B132B] text-white rounded-2xl p-6 space-y-2 border border-[#D4AF37]/20">
              <h3 className="text-sm font-bold font-serif text-[#D4AF37]">Questions about these Terms?</h3>
              <p className="text-[11px] text-[#FAF9F6]/75">Contact our legal team for any clarifications:</p>
              <a href="mailto:legal@indylaw.in" className="text-xs font-bold text-[#D4AF37] hover:text-white transition-colors">
                legal@indylaw.in
              </a>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
